### ISSUE TITLE
HTTPSConnectionPool error

### ISSUE THREAD

**Issue by cvsanthosh** [ConvertAPI/convertapi-python#25]
I am getting the below error when calling convert api to convert pdf file to a text file. Running the command on a compute engine in google cloud.

ps: I am getting similar error on my local desktop as well. Could you please look into and update. 

 raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/anaconda/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/anaconda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/anaconda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/anaconda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='v2.convertapi.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "t1.py", line 51, in <module>
    }, from_format = 'pdf').save_files(DIRECTORY)
  File "/usr/local/anaconda/lib/python3.7/site-packages/convertapi/api.py", line 7, in convert
    return task.run()
  File "/usr/local/anaconda/lib/python3.7/site-packages/convertapi/task.py", line 29, in run
    response = convertapi.client.post(path, params, timeout = timeout)
  File "/usr/local/anaconda/lib/python3.7/site-packages/convertapi/client.py", line 15, in post
    r = requests.post(self.url(path), data = payload, headers = self.headers(), timeout = timeout)
  File "/usr/local/anaconda/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/anaconda/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/anaconda/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/anaconda/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/anaconda/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='v2.convertapi.com', port=443): Read timed out. (read timeout=60)

**Comment by tomasr78** [comment]
Could you try to convert your failed PDF at https://www.convertapi.com/pdf-to-txt
How long does it take to convert the PDF?

**Comment by laurynas-convertapi** [comment]
Should be fixed by https://github.com/ConvertAPI/convertapi-python/pull/30
https://github.com/ConvertAPI/convertapi-python/releases/tag/v1.5.0
